Bug fixes: not freeing queue completely
- Fix the ERROR: Freed queue, but 1 blocks are still allocated
- Handle the bufsize of sp correctly in q_remove_head

In last commit, we accedentally allocate extra memory to old_h,
which need to point to the object q->head,
so when we assign q->head to old_h, it causes memory leak.

And we handle the bufsize of sp correctly.

Without this commit:

        === qtest ===
        $ ./qtest
        cmd> new
        q = []
        cmd> ih hello
        q = [hello]
        cmd> rh hello
        Removed hello from queue
        q = []
        cmd> free
        q = NULL
        ERROR: Freed queue, but 1 blocks are still allocated

With this commit:

        === qtest ===
        $ ./qtest
        cmd> new
        q = []
        cmd> ih hello
        q = [hello]
        cmd> rh hello
        Removed hello from queue
        q = []
        cmd> free
        q = NULL